### ISSUE TITLE
Törlés

### ISSUE THREAD

**Issue by bodand** [kszi2/mk2#15]
Törlés, legalább a pontozásoknál

**Comment by bodand** [comment]
Submission deletion added in ba28e731

**Comment by kisbogdan-kolos** [comment]
Ez miért enhancement? Most kéne egy note-ot törölnöm, de nem lehet.

Igazi bodandsoft...

(Amúgy szar Q-I-es wifi miatt lett kétszer felvéve egy note.)

**Comment by bodand** [comment]
By-design nem lehet note-okat törölni, csak javítani.

**Comment by kisbogdan-kolos** [comment]
Pedig ezekre az esetekre hasznos lenne...

**Comment by bodand** [comment]
Majd akkor a note redesign-nál rakok bele törlést, addig írj valami random dolgot megjegyzésnek.

**Comment by bodand** [comment]
Már lehet (szerintem) mindent törölni. :(
