### ISSUE TITLE
Törtpont levonás

### ISSUE THREAD

**Issue by kisbogdan-kolos** [kszi2/mk2#19]
Lehessen nem egész pontot is levonni. Például ha a fájlkezelésnél két dolog miatt vonok le pontot, akkor ne menjen negatívba a pontszám. Leginkább azért kell, mert az értékelésbe beleírja, hogy hány pont, és az kicsit sus, hogy van 2x1 pont levonás, de összességében csak egyel kevesebb az összpontszám.

**Comment by bodand** [comment]
Majd:tm: (ez jelentősen komplikálja a helyzetet)

**Comment by bodand** [comment]
Van igény általános törtpontra, vagy csak mondjuk fél pontig elég lemenni? Egyáltalán nem adok tört pontot, úgyhogy akik adnak jelentkezzenek. @kisbogdan-kolos nemtom más érdekelt-e

**Comment by kisbogdan-kolos** [comment]
Lehet hogy az lenne a legelegánsabb, hogy ha több pontot vonsz le, mint amennyit a szempont ér, akkor a levont pontokat normalizálja a program, hogy pont elérje a szempont pontszámát.
Pl. ha van valamire 2 pont, és levonok 2 pontot meg még kétszer egyet, akkor azokból lesz 1; 0.5 és 0.5 pont. Csak nem tudom, hogy ennek mennyire van értelme.

Amúgy a fél pont szerintem bőven elég.

**Comment by bodand** [comment]
a normalizálás csak akkor jó, ha minden pont konkrét névvel van ellátva, mint prog1, de pl. prog2-ből van iirc 10 pont arra, hogy OO, ott akkor annyira nem egyértelmű, hogy mit kéne normalizálni és mit nem

meglátom még, hogy mennyire macerás a dolog, de én is elégnek gondoltam a félpontot de azért megkérdeztem

**Comment by bodand** [comment]
v0.16.1 most lett deployolva, elméletileg megvan
megenged .1 pontossággal levonni, de a lépkedő alapból .5-el lép
