### ISSUE TITLE
Pontozási export sorrent

### ISSUE THREAD

**Issue by kisbogdan-kolos** [kszi2/mk2#20]
A pontozási exportban rossz a sorrend.
![image](https://github.com/user-attachments/assets/e3c4b21e-7165-403a-ac58-bba348b9ea59)

**Comment by bodand** [comment]
van egy feature erre, ami magától megoldja, éppen ennek hegesztése okozza a downtimeot

**Comment by bodand** [comment]
(mármint még ha sikerül meghegeszteni, akkor nem lesz magától megjavítva, de amire ténylegesen beteljesedik, addigra meglesz)

**Comment by bodand** [comment]
v0.15.1 elméletileg fix'd
