### ISSUE TITLE
NINCS  KEZET

### ISSUE THREAD

**Issue by berci9ke101** [kszi2/mk2#6]
Attendance sheet-en nincs ékezet. ("ö" betű hibádzik)
![kép](https://github.com/user-attachments/assets/77063f3b-b6ad-483c-999a-0c940d3227ac)

**Comment by bodand** [comment]
Nyitsd meg nem firefoxban.

**Comment by berci9ke101** [comment]
Acrobat Pro DC:
![kép](https://github.com/user-attachments/assets/378f1fb4-26a9-4e18-a2dd-6e627112249d)

**Comment by bodand** [comment]
Okular:
![image](https://github.com/user-attachments/assets/57a04b89-39dc-4bc5-bb19-1889c3b11572)
Edge:
![image](https://github.com/user-attachments/assets/cf7e195b-287e-4962-964d-d712d5620b4a)
